//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeutscheBankKreditrechner.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbLapProjektEntities : DbContext
    {
        public dbLapProjektEntities()
            : base("name=dbLapProjektEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAbschluss> tblAbschluss { get; set; }
        public virtual DbSet<tblArbeitgeber> tblArbeitgeber { get; set; }
        public virtual DbSet<tblBeschaeftigungsArt> tblBeschaeftigungsArt { get; set; }
        public virtual DbSet<tblBranche> tblBranche { get; set; }
        public virtual DbSet<tblFamilienstand> tblFamilienstand { get; set; }
        public virtual DbSet<tblFinanzielleSituation> tblFinanzielleSituation { get; set; }
        public virtual DbSet<tblGeschlecht> tblGeschlecht { get; set; }
        public virtual DbSet<tblIdentifikationsArt> tblIdentifikationsArt { get; set; }
        public virtual DbSet<tblKontaktdaten> tblKontaktdaten { get; set; }
        public virtual DbSet<tblKontoDaten> tblKontoDaten { get; set; }
        public virtual DbSet<tblKreditdaten> tblKreditdaten { get; set; }
        public virtual DbSet<tblLand> tblLand { get; set; }
        public virtual DbSet<tblOrt> tblOrt { get; set; }
        public virtual DbSet<tblPersoenlicheDaten> tblPersoenlicheDaten { get; set; }
        public virtual DbSet<tblSettings> tblSettings { get; set; }
        public virtual DbSet<tblTitel> tblTitel { get; set; }
        public virtual DbSet<tblWohnart> tblWohnart { get; set; }
    }
}
