//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeutscheBankKreditrechner.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBeschaeftigungsArt
    {
        public tblBeschaeftigungsArt()
        {
            this.tblArbeitgeber = new HashSet<tblArbeitgeber>();
        }
    
        public int ID_BeschaeftigungsArt { get; set; }
        public string Beschaeftigungsart { get; set; }
    
        public virtual ICollection<tblArbeitgeber> tblArbeitgeber { get; set; }
    }
}
