//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeutscheBankKreditrechner.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFinanzielleSituation
    {
        public int ID_FinanzielleSituation { get; set; }
        public double NettoEinkommenJährlich { get; set; }
        public Nullable<double> WohnkostenMonatlich { get; set; }
        public Nullable<double> EinkuenfteAlimente { get; set; }
        public Nullable<double> Unterhaltszahlungen { get; set; }
        public Nullable<double> SonstigeAusgabenMonatlich { get; set; }
        public Nullable<double> SonstigeEinnahmenMonatlich { get; set; }
        public Nullable<double> BestehendeRatenVerpflichtungen { get; set; }
    
        public virtual tblPersoenlicheDaten tblPersoenlicheDaten { get; set; }
    }
}
