//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeutscheBankKreditrechner.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKreditdaten
    {
        public int ID_Kredit { get; set; }
        public int Laufzeit { get; set; }
        public double GesamtBetrag { get; set; }
        public double Kreditrate { get; set; }
        public bool istBewilligt { get; set; }
    
        public virtual tblPersoenlicheDaten tblPersoenlicheDaten { get; set; }
    }
}
