//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeutscheBankKreditrechner.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLand
    {
        public tblLand()
        {
            this.tblOrt = new HashSet<tblOrt>();
            this.tblPersoenlicheDaten = new HashSet<tblPersoenlicheDaten>();
        }
    
        public string ID_Land { get; set; }
        public string Land { get; set; }
    
        public virtual ICollection<tblOrt> tblOrt { get; set; }
        public virtual ICollection<tblPersoenlicheDaten> tblPersoenlicheDaten { get; set; }
    }
}
