//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeutscheBankKreditrechner.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrt
    {
        public tblOrt()
        {
            this.tblKontaktdaten = new HashSet<tblKontaktdaten>();
        }
    
        public int ID_Ort { get; set; }
        public string Ort { get; set; }
        public string PLZ { get; set; }
        public string FKLand { get; set; }
    
        public virtual ICollection<tblKontaktdaten> tblKontaktdaten { get; set; }
        public virtual tblLand tblLand { get; set; }
    }
}
