//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeutscheBankKreditrechner.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersoenlicheDaten
    {
        public int ID_PersoenlicheDaten { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public Nullable<int> UHPKinder { get; set; }
        public Nullable<System.DateTime> GeburtsDatum { get; set; }
        public int FKGeschlecht { get; set; }
        public Nullable<int> FKTitel { get; set; }
        public string FKStaatsbuegerschaft { get; set; }
        public Nullable<int> FKFamilienstand { get; set; }
        public Nullable<int> FKWohnart { get; set; }
        public Nullable<int> FKAbschluss { get; set; }
        public Nullable<int> FkIdentifikationsArt { get; set; }
        public string Identifikationsnummer { get; set; }
    
        public virtual tblAbschluss tblAbschluss { get; set; }
        public virtual tblArbeitgeber tblArbeitgeber { get; set; }
        public virtual tblFamilienstand tblFamilienstand { get; set; }
        public virtual tblFinanzielleSituation tblFinanzielleSituation { get; set; }
        public virtual tblGeschlecht tblGeschlecht { get; set; }
        public virtual tblIdentifikationsArt tblIdentifikationsArt { get; set; }
        public virtual tblKontaktdaten tblKontaktdaten { get; set; }
        public virtual tblKontoDaten tblKontoDaten { get; set; }
        public virtual tblKreditdaten tblKreditdaten { get; set; }
        public virtual tblLand tblLand { get; set; }
        public virtual tblTitel tblTitel { get; set; }
        public virtual tblWohnart tblWohnart { get; set; }
    }
}
