//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeutscheBankKreditrechner.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSettings
    {
        public int ID_Settings { get; set; }
        public double FixZins { get; set; }
        public double VariablerZins { get; set; }
        public int MaxLaufzeit { get; set; }
        public int MinLautzeit { get; set; }
        public int MaxKreditBetrag { get; set; }
        public int MinKreditBetreg { get; set; }
    }
}
